name: 'JsBuild'
description: 'build js with npm'
inputs:
  path:
    description: 'project root path'
    required: true
  job-name:
    description: 'Job name'
    required: true
outputs:
  logs:
    description: "logs"
    value: ${{ steps.build.outputs.logs }}
  path:
    description: "output path"
    value: ${{ steps.build.outputs.path }}
runs:
  using: "composite"
  steps:
    - id: build
      name: build
      run: |
        logfile=${{ inputs.job-name }}.build.log
        echo -e "****** LOGFILE: $logfile\n"
        echo -e "****** npm i ******\n" > $logfile
        curdir=$(pwd)
        echo -e "****** npm i 2 ******\n" >> $logfile
        cd ${{ inputs.path }}
        echo -e "****** npm i 3 ******\n" >> $logfile
        npm i >> $logfile
        echo -e "\n****** npm run test ******\n" >> $logfile
        npm run test >> $logfile
        echo "::set-output name=logs::$(echo $logfile)"
        echo "::set-output name=path::$(echo generated/${{ inputs.job-name }})"
        cd ${curdir}
      shell: bash
