name: 'Generate'
description: 'codegen generate'
inputs:
  spec-url:
    description: 'Url of the openapi definition'
    required: true
    default: 'https://petstore3.swagger.io/api/v3/openapi.json'
  language:
    description: 'Language to generate'
    required: true
  job-name:
    description: 'Job name'
    required: true
  options:
    description: 'Language Options'
    required: false
    default: ""
outputs:
  logs:
    description: "logs"
    value: ${{ steps.generate.outputs.logs }}
  output-path:
    description: "output path"
    value: ${{ steps.generate.outputs.path }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.spec-url }}.
      shell: bash
    - id: generate
      name: generate
      run: |
        echo Hi ${{ env.INPUT_SPECURL }}.
        echo Hi2 ${{ env.INPUT_SPEC_URL }}.
        echo Hi3 ${{ env.INPUT_SPEC-URL }}.
        echo "::set-output name=logs::$(echo YATAY)"
        echo "::set-output name=path::$(echo generated/${{ inputs.job-name }})"
    - run: chmod +x ${{ github.action_path }}/generate.sh
      shell: bash
    - run: ${{ github.action_path }}/generate.sh ${{ inputs.language }} ${{ inputs.job-name }} ${{ inputs.spec-url }} ${{ inputs.options }}
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
