name: Test action

on:
  workflow_dispatch:
    branches: ["master", "test-framework", "3.0.0"]

jobs:

  build-codegen:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - uses: actions/checkout@v2
      - name: My first step
        id: aaaa
        uses: ./.github/actions/generate
        with:
          language: "javascript"
          job-name: "js-petstore-v3"
      - run: |
          echo "AAA ${{ steps.aaaa.outputs.path }}"
          echo "AAA ${{ steps.aaaa.outputs.logs }}"
