name: .NET Test

on:
  workflow_dispatch:
    branches: ["master", "test-framework", "3.0.0"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cd sample dir
        run: cd ./samples/client/petstore/csharp/SwaggerClient
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
